# Generated by Django 2.0.7 on 2021-01-02 08:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import hospital.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_com', models.CharField(default=hospital.models.contracts.individual, max_length=30)),
                ('con_amt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('con_equip', models.CharField(default=hospital.models.contracts.individual, max_length=30)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(default=hospital.models.departments.individual, max_length=30)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='instruments',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(default=hospital.models.instruments.individual, max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
            ],
            options={
                'db_table': 'instruments',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_quan', models.IntegerField(default=0)),
                ('Con_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.contracts')),
                ('Dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments')),
                ('Inst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.instruments')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('depa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.order')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
